info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'

grails:
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
  quartz:
    autoStartup: true
    jdbcStore: false
    waitForJobsToCompleteOnShutdown: true
    exposeSchedulerInRepository: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: rahat@gmail.com
    password: passwprd
    props:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
#  quartz:
#    autoStartup: true
#    jdbcStore: false

  views:
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
    default:
      codec: html

  codegen:
    defaultPackage: proj.assignment

  profile: web

dataSource:
  driverClassName: org.h2.Driver
  username: sa
  password: ''
  pooled: true
  jmxExport: true

environments:
  development:
    dataSource:
      dbCreate: update
      url: jdbc:h2:file:./h2db/devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
      driverClassName: org.h2.Driver
      username: sa
      password: ''
      dialect: org.hibernate.dialect.H2Dialect

    server:
      servlet:
        context-path: /
      error:
        include-message: always

    spring:
      h2:
        console:
          enabled: true
          path: /h2-console

    hibernate:
      show_sql: true
      format_sql: true

  test:
    dataSource:
      dbCreate: update
      url: jdbc:h2:mem:testDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
      driverClassName: org.h2.Driver
      username: sa
      password: ''
      dialect: org.hibernate.dialect.H2Dialect

  production:
    dataSource:
      dbCreate: update
      url: jdbc:h2:file:./h2db/prodDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
      driverClassName: org.h2.Driver
      username: sa
      password: ''
      dialect: org.hibernate.dialect.H2Dialect
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2

hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
